### PR TITLE
Inherit Address from str. Rename Address to Base32Address. Make API m…

### PR DESCRIPTION
**Pull request by darwintree**
…ore convenient.

- - -
This change is [Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: all files reviewed, 2 unresolved discussions (waiting on @darwintree)

___
*[`cfx_address/address.py` line 42 at r1](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9HT1VS8Ac7j7UAfdAU:-N9HT1VS8Ac7j7UAfdAV:b-r5mkfh) ([raw file](https://github.com/conflux-fans/cfx-address/blob/398cba68156bde543ac58f1d58ce01220a7e9114/cfx_address/address.py#L42)):*
> ```Python
>     COMMON_NET_PREFIX = "net"
> 
>     TYPE_NULL = "type.null"
> ```

Recommend not add "type." in AddressType to keep consistent with other SDKs
___
*[`cfx_address/address.py` line 243 at r1](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9GklaC-2YcE97UTE3M:-N9GklaC-2YcE97UTE3N:b-waxokd) ([raw file](https://github.com/conflux-fans/cfx-address/blob/398cba68156bde543ac58f1d58ce01220a7e9114/cfx_address/address.py#L243)):*
> ```Python
>         splits = base32_address.split(cls.DELIMITER)
>         if len(splits) == 3 and splits[1] != address_type:
>             if splits[1] in cls.KNOWN_TYPES:
> ```

What's the check logic here ?

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @Pana)

___
*[`cfx_address/address.py` line 42 at r1](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9HT1VS8Ac7j7UAfdAU:-N9UTPud3u5wnRanl4Mv:b-896fix) ([raw file](https://github.com/conflux-fans/cfx-address/blob/398cba68156bde543ac58f1d58ce01220a7e9114/cfx_address/address.py#L42)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

Recommend not add "type." in AddressType to keep consistent with other SDKs
</blockquote></details>

Done.
___
*[`cfx_address/address.py` line 243 at r1](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9GklaC-2YcE97UTE3M:-N9UTjSg0YUXNDQUuFsh:bpw199u) ([raw file](https://github.com/conflux-fans/cfx-address/blob/398cba68156bde543ac58f1d58ce01220a7e9114/cfx_address/address.py#L243)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

What's the check logic here ?
</blockquote></details>

cip-37 #Decoding
        6.Verify optional fields:

        If the optional fields contain type.*: Verify the address-type according to the specification above.
        Unknown options (options other than type.*) should be ignored.
        
which means
        if address field is not expected, reject if the address field is a known one, else ignore
        e.g.
        valid CFX:TYPE.USER:AATP533CG7D0AGBD87KZ48NJ1MPNKCA8BE7GGP3VPU
        invalid CFX:TYPE.NULL:AATP533CG7D0AGBD87KZ48NJ1MPNKCA8BE7GGP3VPU
        ignore(but valid) CFX:GOD:AATP533CG7D0AGBD87KZ48NJ1MPNKCA8BE7GGP3VPU

**Review by Pana — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Review by Pana — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @darwintree and @Pana)

___
*[`cfx_address/address.py` line 120 at r3](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9W5Ziu5F-ng9_n9cCL:-N9W5Ziu5F-ng9_n9cCM:bs4u6pf) ([raw file](https://github.com/conflux-fans/cfx-address/blob/da79dfeec39dd20c775ff089c863a8108d5e3874/cfx_address/address.py#L120)):*
> ```Python
>     
>     @property
>     def short(self) -> str:
> ```

Also, there is a compressed mode for short method

**Review by darwintree — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: 2 of 24 files reviewed, 1 unresolved discussion (waiting on @Pana)

___
*[`cfx_address/address.py` line 120 at r3](https://reviewable.io/reviews/conflux-fans/cfx-address/1#-N9W5Ziu5F-ng9_n9cCL:-N9ePqiP82fZITTE3V3m:b-896fix) ([raw file](https://github.com/conflux-fans/cfx-address/blob/da79dfeec39dd20c775ff089c863a8108d5e3874/cfx_address/address.py#L120)):*
<details><summary><i>Previously, Pana (Pana) wrote…</i></summary><blockquote>

Also, there is a compressed mode for short method
</blockquote></details>

Done.

**Review by Pana — COMMENTED** [review]
> Reviewed 20 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @Pana)

**Review by Pana — APPROVED** [review]
> Reviewed 2 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/conflux-fans/cfx-address/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darwintree)

**Pull request merged**
